// tacnn_schema.h -- generated by tools/tacrl/schema_gen.py in the ja2mod
// repository from tools/tacsim/obs/spec.py.  Do not edit by hand; edit the
// Python spec and regenerate.  Schema version 2, layout hash
// 0x18220011.
//
// Every struct is packed, little-endian plain data.  The same bytes are
// written to the decision log, sent over the sidecar pipe and read back by
// tools/tacsim/logreader.py, so a change here is a change of
// TACNN_SCHEMA_VERSION.
//
// ja2mod 2026-09-15: added. 2026-09-16: schema 2, the embedded record, the
// network's fixed sizes and the kind compatibility table.
#ifndef TACNN_SCHEMA_H
#define TACNN_SCHEMA_H

#include <stdint.h>
#include <stddef.h>

#define TACNN_SCHEMA_HASH 0x18220011u
#define TACNN_MAGIC_RECORD 0x4E434154u
#define TACNN_MAGIC_REQUEST 0x52434154u
#define TACNN_MAGIC_RESPONSE 0x41434154u

// sizes
#define TACNN_SCHEMA_VERSION 2
#define TACNN_PATCH 20
#define TACNN_PATCH_RADIUS 10
#define TACNN_MEDIUM_SCALE 2
#define TACNN_PATCH_CHANNELS 16
#define TACNN_GLOBAL 16
#define TACNN_GLOBAL_TILES_PER_CELL 10
#define TACNN_GLOBAL_CHANNELS 6
#define TACNN_ENTITIES 20
#define TACNN_ENTITY_DIMS 40
#define TACNN_SELF_DIMS 56
#define TACNN_NUM_ROLES 8
#define TACNN_PERSONALITY_DIMS 8
#define TACNN_CANDIDATES 48
#define TACNN_CANDIDATE_DIMS 28
#define TACNN_ACTION_TYPES 24
#define TACNN_AIM_LEVELS 6
#define TACNN_FIRE_MODES 3
#define TACNN_STANCES 3
#define TACNN_MAX_SOLDIERS 256
#define TACNN_NO_UNIT 255
#define TACNN_HIDDEN 192
#define TACNN_INBOX 4
#define TACNN_MESSAGE_DIMS 24
#define TACNN_SIGNATURE_DIMS 12
#define TACNN_RADIO_RANGE_TILES 40

enum {
    TACNN_ACT_END_TURN = 0,
    TACNN_ACT_HOLD = 1,
    TACNN_ACT_MOVE_RUN = 2,
    TACNN_ACT_MOVE_WALK = 3,
    TACNN_ACT_MOVE_SWAT = 4,
    TACNN_ACT_TAKE_COVER = 5,
    TACNN_ACT_SEEK_OPPONENT = 6,
    TACNN_ACT_SEEK_NOISE = 7,
    TACNN_ACT_SEEK_FRIEND = 8,
    TACNN_ACT_FLANK_LEFT = 9,
    TACNN_ACT_FLANK_RIGHT = 10,
    TACNN_ACT_WITHDRAW = 11,
    TACNN_ACT_RUN_AWAY = 12,
    TACNN_ACT_FIRE_GUN = 13,
    TACNN_ACT_SUPPRESS = 14,
    TACNN_ACT_TOSS_PROJECTILE = 15,
    TACNN_ACT_THROW_KNIFE = 16,
    TACNN_ACT_KNIFE_STAB = 17,
    TACNN_ACT_RELOAD = 18,
    TACNN_ACT_CHANGE_STANCE = 19,
    TACNN_ACT_CHANGE_FACING = 20,
    TACNN_ACT_RED_ALERT = 21,
    TACNN_ACT_DOCTOR = 22,
    TACNN_ACT_CLIMB = 23,
    TACNN_ACT_COUNT = 24
};

enum {
    TACNN_CAND_EMPTY = 0,
    TACNN_CAND_ENEMY = 1,
    TACNN_CAND_TEAMMATE = 2,
    TACNN_CAND_COVER = 3,
    TACNN_CAND_ADVANCE = 4,
    TACNN_CAND_FLANK = 5,
    TACNN_CAND_RETREAT = 6,
    TACNN_CAND_NOISE = 7,
    TACNN_CAND_SAMPLE = 8,
    TACNN_CAND_WATCHED = 9,
    TACNN_CAND_SELF = 10,
    TACNN_CAND_OBJECTIVE = 11,
    TACNN_CAND_COUNT = 12
};

enum {
    TACNN_SRC_LEGACY = 0,
    TACNN_SRC_SIDECAR = 1,
    TACNN_SRC_EMBEDDED = 2,
    TACNN_SRC_COUNT = 3
};

enum {
    TACNN_REC_BATTLE_START = 0,
    TACNN_REC_DECISION = 1,
    TACNN_REC_OUTCOME = 2,
    TACNN_REC_EPISODE_END = 3,
    TACNN_REC_EMBEDDED = 4,
    TACNN_REC_COUNT = 5
};

enum {
    TACNN_ROLE_RIFLEMAN = 0,
    TACNN_ROLE_SNIPER = 1,
    TACNN_ROLE_MARKSMAN = 2,
    TACNN_ROLE_MACHINEGUNNER = 3,
    TACNN_ROLE_RADIO_OPERATOR = 4,
    TACNN_ROLE_MEDIC = 5,
    TACNN_ROLE_MORTAR_OR_GL = 6,
    TACNN_ROLE_OFFICER = 7,
    TACNN_ROLE_COUNT = 8
};

enum {
    TACNN_OUTCOME_UNKNOWN = 0,
    TACNN_OUTCOME_ENEMY_WON = 1,
    TACNN_OUTCOME_PLAYER_WON = 2,
    TACNN_OUTCOME_RETREAT = 3,
    TACNN_OUTCOME_ABORTED = 4,
    TACNN_OUTCOME_COUNT = 5
};

enum {
    TACNN_MODE_OFF = 0,
    TACNN_MODE_SIDECAR = 1,
    TACNN_MODE_EMBEDDED = 2,
    TACNN_MODE_COUNT = 3
};

#pragma pack(push, 1)

struct TacnnObservation {
    uint8_t fine[16][20][20];
    uint8_t medium[16][20][20];
    uint8_t global_map[6][16][16];
    float entities[20][40];
    uint8_t entity_mask[20];
    uint8_t entity_id[20];
    float self_vec[56];
    uint8_t role;
    uint8_t stage;
    uint8_t facing;
    uint8_t level;
    int32_t gridno;
    float personality[8];
};

struct TacnnActionMask {
    uint8_t type[24];
    uint8_t target[48];
    uint8_t aim[6];
    uint8_t mode[3];
    uint8_t stance[3];
};

struct TacnnCandidateSet {
    float features[48][28];
    int32_t gridno[48];
    int8_t level[48];
    uint8_t kind[48];
    uint8_t unit_id[48];
    uint8_t ap_cost[48];
};

struct TacnnPolicyAction {
    uint8_t type;
    uint8_t target_slot;
    uint8_t aim;
    uint8_t mode;
    uint8_t stance;
    uint8_t decline;
    uint16_t reserved;
    float value;
    float logits_checksum;
};

struct TacnnRecordHeader {
    uint32_t magic;
    uint16_t record_type;
    uint16_t schema_version;
    uint32_t payload_bytes;
    uint32_t schema_hash;
};

struct TacnnBattleStart {
    uint32_t battle_lo;
    uint32_t battle_hi;
    int16_t sector_x;
    int16_t sector_y;
    int8_t sector_z;
    uint8_t difficulty;
    uint16_t turn;
    uint32_t ai_seed;
    uint8_t map_name[16];
};

struct TacnnDecision {
    uint32_t battle_lo;
    uint32_t battle_hi;
    uint32_t decision_index;
    uint16_t turn;
    uint8_t team;
    uint8_t soldier_id;
    uint8_t source;
    int8_t engine_action;
    int8_t target_level;
    int8_t aim_time;
    int32_t engine_action_data;
    int16_t action_points;
    uint16_t elapsed_us;
};

struct TacnnOutcome {
    uint32_t battle_lo;
    uint32_t battle_hi;
    uint32_t decision_index;
    uint16_t turn;
    uint8_t attacker;
    uint8_t victim;
    uint8_t attacker_team;
    uint8_t victim_team;
    uint8_t victim_died;
    uint8_t reason;
    int16_t damage;
    int16_t breath;
};

struct TacnnEpisodeEnd {
    uint32_t battle_lo;
    uint32_t battle_hi;
    uint16_t turns;
    uint8_t outcome;
    uint8_t survivors_enemy;
    uint8_t survivors_player;
    uint8_t survivors_militia;
    uint16_t decisions;
    int32_t damage_dealt;
    int32_t damage_taken;
};

struct TacnnEmbedded {
    uint32_t battle_lo;
    uint32_t battle_hi;
    uint32_t decision_index;
    uint8_t soldier_id;
    uint8_t reserved;
    uint16_t infer_us;
    float h_in[192];
    float inbox_msg[4][24];
    float inbox_sig[4][12];
    uint8_t inbox_mask[4];
    float type_logits[24];
    float target_logits[48];
    float aim_logits[6];
    float mode_logits[3];
    float stance_logits[3];
    float message[24];
    float signature[12];
    float h_out[192];
};

struct TacnnSidecarRequest {
    uint32_t magic;
    uint16_t schema_version;
    uint16_t flags;
    uint32_t schema_hash;
    uint32_t sequence;
    uint32_t battle_lo;
    uint32_t battle_hi;
    uint32_t decision_index;
    uint16_t turn;
    uint8_t team;
    uint8_t soldier_id;
    uint16_t timeout_ms;
    uint16_t reserved;
};

struct TacnnSidecarResponse {
    uint32_t magic;
    uint32_t sequence;
    uint32_t schema_hash;
    TacnnPolicyAction policy_action;
};

#pragma pack(pop)

// the Python spec computed these sizes; a mismatch means the compiler
// padded something and the log would be unreadable
static_assert(sizeof(TacnnObservation) == 17840, "TacnnObservation layout");
static_assert(sizeof(TacnnActionMask) == 84, "TacnnActionMask layout");
static_assert(sizeof(TacnnCandidateSet) == 5760, "TacnnCandidateSet layout");
static_assert(sizeof(TacnnPolicyAction) == 16, "TacnnPolicyAction layout");
static_assert(sizeof(TacnnRecordHeader) == 16, "TacnnRecordHeader layout");
static_assert(sizeof(TacnnBattleStart) == 36, "TacnnBattleStart layout");
static_assert(sizeof(TacnnDecision) == 28, "TacnnDecision layout");
static_assert(sizeof(TacnnOutcome) == 24, "TacnnOutcome layout");
static_assert(sizeof(TacnnEpisodeEnd) == 24, "TacnnEpisodeEnd layout");
static_assert(sizeof(TacnnEmbedded) == 2612, "TacnnEmbedded layout");
static_assert(sizeof(TacnnSidecarRequest) == 36, "TacnnSidecarRequest layout");
static_assert(sizeof(TacnnSidecarResponse) == 28, "TacnnSidecarResponse layout");

// blob order after the fixed part of a decision record and a request
#define TACNN_DECISION_BLOB_BYTES (sizeof(TacnnObservation) + sizeof(TacnnActionMask) + sizeof(TacnnCandidateSet) + sizeof(TacnnPolicyAction))
#define TACNN_REQUEST_BLOB_BYTES (sizeof(TacnnObservation) + sizeof(TacnnActionMask) + sizeof(TacnnCandidateSet))

// which candidate kinds an action type may point at
// (tools/tacsim/obs/candidates.py ACTION_TARGET_KINDS); row TACNN_ACT_*,
// column TACNN_CAND_*, an all-zero row is an action without a target.
// The policy's target head is read through this table on both sides.
static const uint8_t tacnn_kind_compat[TACNN_ACT_COUNT][TACNN_CAND_COUNT] = {
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },  // END_TURN
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },  // HOLD
    { 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1 },  // MOVE_RUN
    { 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1 },  // MOVE_WALK
    { 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1 },  // MOVE_SWAT
    { 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0 },  // TAKE_COVER
    { 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },  // SEEK_OPPONENT
    { 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 },  // SEEK_NOISE
    { 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 },  // SEEK_FRIEND
    { 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },  // FLANK_LEFT
    { 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },  // FLANK_RIGHT
    { 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0 },  // WITHDRAW
    { 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0 },  // RUN_AWAY
    { 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },  // FIRE_GUN
    { 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0 },  // SUPPRESS
    { 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0 },  // TOSS_PROJECTILE
    { 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },  // THROW_KNIFE
    { 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },  // KNIFE_STAB
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },  // RELOAD
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },  // CHANGE_STANCE
    { 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1 },  // CHANGE_FACING
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },  // RED_ALERT
    { 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 },  // DOCTOR
    { 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1 },  // CLIMB
};

// the engine AI_ACTION_* each policy action type maps to, indexed by
// TACNN_ACT_*; kept as text so the glue can assert the mapping
#ifdef TACNN_WANT_NAMES
static const char* const tacnn_action_names[TACNN_ACT_COUNT] = {
    "END_TURN",
    "HOLD",
    "MOVE_RUN",
    "MOVE_WALK",
    "MOVE_SWAT",
    "TAKE_COVER",
    "SEEK_OPPONENT",
    "SEEK_NOISE",
    "SEEK_FRIEND",
    "FLANK_LEFT",
    "FLANK_RIGHT",
    "WITHDRAW",
    "RUN_AWAY",
    "FIRE_GUN",
    "SUPPRESS",
    "TOSS_PROJECTILE",
    "THROW_KNIFE",
    "KNIFE_STAB",
    "RELOAD",
    "CHANGE_STANCE",
    "CHANGE_FACING",
    "RED_ALERT",
    "DOCTOR",
    "CLIMB",
};
static const char* const tacnn_action_engine_names[TACNN_ACT_COUNT] = {
    "AI_ACTION_END_TURN",
    "AI_ACTION_NONE",
    "AI_ACTION_RUN",
    "AI_ACTION_WALK",
    "AI_ACTION_GET_CLOSER",
    "AI_ACTION_TAKE_COVER",
    "AI_ACTION_SEEK_OPPONENT",
    "AI_ACTION_SEEK_NOISE",
    "AI_ACTION_SEEK_FRIEND",
    "AI_ACTION_FLANK_LEFT",
    "AI_ACTION_FLANK_RIGHT",
    "AI_ACTION_WITHDRAW",
    "AI_ACTION_RUN_AWAY",
    "AI_ACTION_FIRE_GUN",
    "AI_ACTION_FIRE_GUN",
    "AI_ACTION_TOSS_PROJECTILE",
    "AI_ACTION_THROW_KNIFE",
    "AI_ACTION_KNIFE_STAB",
    "AI_ACTION_RELOAD_GUN",
    "AI_ACTION_CHANGE_STANCE",
    "AI_ACTION_CHANGE_FACING",
    "AI_ACTION_RED_ALERT",
    "AI_ACTION_DOCTOR",
    "AI_ACTION_CLIMB_ROOF",
};
// 0 none, 1 tile, 2 unit
static const uint8_t tacnn_action_target_kind[TACNN_ACT_COUNT] = {
    0, 0, 1, 1, 1, 1, 2, 1, 2, 2, 2, 1, 1, 2, 1, 1, 2, 2, 0, 0, 1, 0, 2, 1
};
#endif // TACNN_WANT_NAMES

#endif // TACNN_SCHEMA_H
